version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data  # Mount the host directory to the container
    environment:
      - REDIS_URL=redis://redis:6379/0
      - BREVO_URL=${BREVO_URL}
      - BREVO_API_KEY=${BREVO_API_KEY}
    depends_on:
      - redis
